name: XiaoMi Video Reward
on:
  workflow_dispatch:  # 允许手动触发
  # schedule:
  #   - cron: '0 1 * * *'    # UTC 1:00 = 北京时间 9:00

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Execute script
        run: python xiaomi.py
        env:
          XIAOMI_ACCOUNTS: ${{ secrets.XIAOMI_ACCOUNTS }}
